<?php
$config["uri_segment"] = 3;
//$config['query_string_segment'] = 'page';
//$config['full_tag_open'] = '<div class="pagination"><ul>';
//$config['full_tag_close'] = '</ul></div><!--pagination-->';
//$config['first_link'] = '&laquo; First';
//$config['first_tag_open'] = '<li class="prev page">';
//$config['first_tag_close'] = '</li>';
//$config['last_link'] = 'Last &raquo;';
//$config['last_tag_open'] = '<li class="next page">';
//$config['last_tag_close'] = '</li>';
//$config['next_link'] = 'Next &rarr;';
//$config['next_tag_open'] = '<li class="next page">';
//$config['next_tag_close'] = '</li>';
//$config['prev_link'] = '&larr; Previous';
//$config['prev_tag_open'] = '<li class="prev page">';
//$config['prev_tag_close'] = '</li>';
//$config['cur_tag_open'] = '<li class="active"><a href="">';
//$config['cur_tag_close'] = '</a></li>';
//$config['num_tag_open'] = '<li class="page">';
//$config['num_tag_close'] = '</li>';
// $config['display_pages'] = FALSE;
// 
//$config['anchor_class'] = 'follow_link';

$config["full_tag_open"] = '<ul class="pagination">';
$config["full_tag_close"] = '</ul>';	
$config["first_link"] = "&laquo;";
$config["first_tag_open"] = "<li>";
$config["first_tag_close"] = "</li>";
$config["last_link"] = "&raquo;";
$config["last_tag_open"] = "<li>";
$config["last_tag_close"] = "</li>";
$config['next_link'] = '&gt;';
$config['next_tag_open'] = '<li>';
$config['next_tag_close'] = '<li>';
$config['prev_link'] = '&lt;';
$config['prev_tag_open'] = '<li>';
$config['prev_tag_close'] = '<li>';
$config['cur_tag_open'] = '<li class="active"><a href="#">';
$config['cur_tag_close'] = '</a></li>';
$config['num_tag_open'] = '<li>';
$config['num_tag_close'] = '</li>';
